# Generated by Django 6.0.4 on 2026-04-24 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('width_mm', models.FloatField(default=50.0)),
                ('height_mm', models.FloatField(default=30.0)),
                ('dpi', models.IntegerField(default=203)),
                ('columns', models.IntegerField(default=1)),
                ('gap_mm', models.FloatField(default=3.0)),
                ('print_speed', models.IntegerField(default=4)),
                ('print_darkness', models.IntegerField(default=8)),
                ('canvas_json', models.TextField(blank=True, default='{}')),
                ('btw_file', models.FileField(blank=True, null=True, upload_to='designs/btw/')),
                ('prn_file', models.FileField(blank=True, null=True, upload_to='designs/prn/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
